name: Regression Tests on Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Install project dependencies
        run: npm install

      - name: Run regression tests
        run: npx cypress run --env TAGS="@regression"

      - name: Generate test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            cypress/reports/
            cypress/screenshots/ 
